site_name: SANS OSINT SEC487 Start Page
copyright: '©2021 Micah Hoffman'
site_description: 'SANS OSINT SEC487 Start Page'
site_author: 'Micah Hoffman'

theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

plugins:
  - search

### FILES LISTED LATER WILL OVERRIDE DEFAULTS AND FILES LISTED EARLIER ###
extra_css:
  - css/html.css
  - css/jquery.fancybox.min.css

extra_javascript:
  - js/jquery-3.4.1.min.js
  - js/jquery.fancybox.min.js